apiVersion: v1
kind: ReplicationController
metadata:
  name: flaskr-nginx
  labels:
    app: flaskr-nginx
spec:
  replicas: 1
  selector:
    app: flaskr-nginx
  template:
    metadata:
      labels:
        app: flaskr-nginx
    spec:
      containers:
      - name: nginx
        image: registry:5000/flaskr-nginx
        ports:
        - containerPort: 80
