apiVersion: v1
kind: Service
metadata:
  name: flaskr-nginx
  labels:
    app: flaskr-nginx
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    nodePort: 30080
  selector:
    app: flaskr-nginx
  type: NodePort
