apiVersion: v1
kind: ReplicationController
metadata:
  name: flaskr
  labels:
    app: flaskr
spec:
  replicas: 1
  selector:
    app: flaskr
  template:
    metadata:
      labels:
        app: flaskr
    spec:
      containers:
      - name: flaskr
        image: registry:5000/flaskr
        ports:
        - containerPort: 5000
