apiVersion: v1
kind: Service
metadata:
  name: learn-kubernetes
  labels:
    app: learn-kubernetes
spec:
  ports:
  - name: notebook
    port: 8888
    protocol: TCP
    nodePort: 30888
  selector:
    app: learn-kubernetes
  type: NodePort
