apiVersion: v1
kind: Service
metadata:
  name: flaskr
  labels:
    app: flaskr
spec:
  ports:
  - port: 5000
    name: http
    protocol: TCP
    nodePort: 30080
  selector:
    app: flaskr
  type: NodePort
