apiVersion: v1
kind: Service
metadata:
  name: gogs
  labels:
    app: gogs
spec:
  ports:
  - port: 3000
    name: gogs-http
    protocol: TCP
    nodePort: 30300
  - port: 22
    name: gogs-ssh
    protocol: TCP
    nodePort: 30322
  selector:
    app: gogs
  type: NodePort
